-- Canonical secondary track registry for all 22 Arab countries.
-- Track presence is separate from lesson-level completeness.
create table if not exists public.secondary_tracks (
  id uuid primary key default gen_random_uuid(),
  country_code text not null,
  country_name_ar text not null,
  system_name_ar text not null,
  track_name_ar text not null,
  grades integer[],
  status text not null default 'active',
  arabic_policy text,
  lesson_coverage text not null default 'unknown',
  academic_year text not null,
  source_urls jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(country_code, system_name_ar, track_name_ar, academic_year)
);

alter table public.secondary_tracks enable row level security;

drop policy if exists "secondary_tracks_public_read" on public.secondary_tracks;
create policy "secondary_tracks_public_read"
on public.secondary_tracks
for select
using (is_active = true);

create index if not exists secondary_tracks_country_year_idx
on public.secondary_tracks(country_code, academic_year);

insert into public.secondary_tracks (
  country_code, country_name_ar, system_name_ar, track_name_ar, grades,
  status, arabic_policy, lesson_coverage, academic_year, source_urls
)
values
('BH','مملكة البحرين','الثانوي العام/النوعي','توحيد المسارات',NULL,'active','specific-or-shared-by-course','partial','2026-2027','["https://edunet.bh/Econtent/LessonsGuide","https://edunet.bh/manual/plans1-2026-2027/Arabic/Plan2.pdf"]'::jsonb),
('BH','مملكة البحرين','الثانوي العام/النوعي','التعليم الديني',NULL,'active','partly-shared-with-unified','partial','2026-2027','["https://edunet.bh/Econtent/LessonsGuide","https://edunet.bh/manual/plans1-2026-2027/Arabic/Plan2.pdf"]'::jsonb),
('BH','مملكة البحرين','الثانوي العام/النوعي','التعليم الفني والمهني',NULL,'active','needs-detailed-current-arabic-plan','partial','2026-2027','["https://edunet.bh/Econtent/LessonsGuide","https://edunet.bh/manual/plans1-2026-2027/Arabic/Plan2.pdf"]'::jsonb),
('BH','مملكة البحرين','الثانوي العام/النوعي','المسار الإداري والتكنولوجي - الهندسي',NULL,'active','needs-detailed-current-arabic-plan','partial','2026-2027','["https://edunet.bh/Econtent/LessonsGuide","https://edunet.bh/manual/plans1-2026-2027/Arabic/Plan2.pdf"]'::jsonb),
('BH','مملكة البحرين','الثانوي العام/النوعي','التعليم المستمر',NULL,'active','needs-detailed-current-arabic-plan','partial','2026-2027','["https://edunet.bh/Econtent/LessonsGuide","https://edunet.bh/manual/plans1-2026-2027/Arabic/Plan2.pdf"]'::jsonb),
('EG','مصر','الثانوية العامة','الصف الأول الثانوي — مشترك',ARRAY[10]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','الثانوية العامة','الشعبة العلمية',ARRAY[11]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','الثانوية العامة','الشعبة الأدبية',ARRAY[11,12]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','الثانوية العامة','علوم',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','الثانوية العامة','رياضيات',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','البكالوريا المصرية','الطب وعلوم الحياة',NULL,'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','البكالوريا المصرية','الهندسة وعلوم الحاسب',NULL,'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','البكالوريا المصرية','الأعمال',NULL,'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('EG','مصر','البكالوريا المصرية','الآداب والفنون',NULL,'active','','generic-or-partial','2026-2027','["https://moe.gov.eg/ar/elearningenterypage/e-learning/"]'::jsonb),
('JO','الأردن','المسار الأكاديمي','الأكاديمي',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','تكنولوجيا المعلومات',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الأعمال',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الضيافة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','السفر والسياحة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الإعلام الإبداعي/الوسائط المتعددة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','التصميم',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الهندسة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الرياضة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الصحة والرعاية الاجتماعية',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الزراعة',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('JO','الأردن','المسار المهني والتقني BTEC','الإنشاءات',NULL,'active','','partial','2026-2027','["https://nccd.gov.jo/Ar/Pages/textbooks","https://nccd.gov.jo/Ar/Pages/Publications/?MaterialStudy=92"]'::jsonb),
('LY','ليبيا','التعليم الثانوي العام','القسم العلمي',NULL,'active','','partial','2026-2027','["https://cerc.moe.gov.ly/educational-curricul/"]'::jsonb),
('LY','ليبيا','التعليم الثانوي العام','القسم الأدبي',NULL,'active','','partial','2026-2027','["https://cerc.moe.gov.ly/educational-curricul/"]'::jsonb),
('LY','ليبيا','التعليم الديني','الثانوي الديني',NULL,'active','needs-detailed-current-source','partial','2026-2027','["https://cerc.moe.gov.ly/educational-curricul/"]'::jsonb),
('PS','فلسطين','الثانوي','علمي',NULL,'active','','generic-or-partial','2026-2027','["https://moe.edu.ps/pal-books","https://moe.edu.ps/class12/books"]'::jsonb),
('PS','فلسطين','الثانوي','علوم إنسانية',NULL,'active','','generic-or-partial','2026-2027','["https://moe.edu.ps/pal-books","https://moe.edu.ps/class12/books"]'::jsonb),
('PS','فلسطين','الثانوي','ريادة وأعمال',NULL,'active','','generic-or-partial','2026-2027','["https://moe.edu.ps/pal-books","https://moe.edu.ps/class12/books"]'::jsonb),
('PS','فلسطين','الثانوي','صناعي',NULL,'active','','generic-or-partial','2026-2027','["https://moe.edu.ps/pal-books","https://moe.edu.ps/class12/books"]'::jsonb),
('PS','فلسطين','الثانوي','شرعي',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://moe.edu.ps/pal-books","https://moe.edu.ps/class12/books"]'::jsonb),
('TN','تونس','التعليم الثانوي','الآداب',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','الرياضيات',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','العلوم التجريبية',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','الاقتصاد والتصرف',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','العلوم التقنية',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','علوم الإعلامية',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('TN','تونس','التعليم الثانوي','الرياضة',NULL,'active','','book-level','2026-2027','["https://cnp.com.tn/arabic/annee-actuelle/listeOfficielle.htm"]'::jsonb),
('LB','لبنان','الثانوي العام','الأولى الثانوية — مشترك',ARRAY[10]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','إنسانيات',ARRAY[11]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','علوم',ARRAY[11]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','آداب وإنسانيات',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','اجتماع واقتصاد',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','علوم عامة',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','الثانوي العام','علوم الحياة',ARRAY[12]::integer[],'active','','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('LB','لبنان','التعليم المهني والتقني','الثانوي التقني/المهني',NULL,'active','needs-detailed-current-arabic-source','generic-or-partial','2026-2027','["https://www.crdp.org/books-pdf","https://www.crdp.org/curriculum-content_details/%D9%85%D9%86%D9%87%D8%AC-%D8%A7%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%88%D8%A2%D8%AF%D8%A7%D8%A8%D9%87%D8%A7/%D8%B9%D8%B1%D8%A8%D9%8A"]'::jsonb),
('MR','موريتانيا','الثانوي','الشعبة الأدبية',ARRAY[11,12,13]::integer[],'active','','detailed-partial-to-strong','2026-2027','["https://koutoubi.mr/"]'::jsonb),
('MR','موريتانيا','الثانوي','الشعبة العلمية',ARRAY[11,12,13]::integer[],'active','','detailed-partial-to-strong','2026-2027','["https://koutoubi.mr/"]'::jsonb),
('MR','موريتانيا','الثانوي','السنة الرابعة الثانوية — مشترك',ARRAY[10]::integer[],'active','','detailed-partial-to-strong','2026-2027','["https://koutoubi.mr/"]'::jsonb),
('OM','عُمان','التعليم الأساسي','الصف العاشر — مشترك',ARRAY[10]::integer[],'active','','book-level-and-partial-detailed','2026-2027','["https://home.moe.gov.om/library/171","https://ict.moe.gov.om/eBooks/index.php"]'::jsonb),
('OM','عُمان','التعليم ما بعد الأساسي','المسار العام مع المواد الاختيارية',ARRAY[11,12]::integer[],'active','','book-level-and-partial-detailed','2026-2027','["https://home.moe.gov.om/library/171","https://ict.moe.gov.om/eBooks/index.php"]'::jsonb),
('OM','عُمان','التعليم ما بعد الأساسي','المسار المهني والتقني',ARRAY[11,12]::integer[],'active','','book-level-and-partial-detailed','2026-2027','["https://home.moe.gov.om/library/171","https://ict.moe.gov.om/eBooks/index.php"]'::jsonb),
('OM','عُمان','التعليم ما بعد الأساسي','المعاهد الإسلامية',ARRAY[11,12]::integer[],'active','','book-level-and-partial-detailed','2026-2027','["https://home.moe.gov.om/library/171","https://ict.moe.gov.om/eBooks/index.php"]'::jsonb),
('AE','الإمارات العربية المتحدة','الثانوية','المسار العام',NULL,'active','','generic','2026-2027','["https://www.moe.gov.ae/","https://u.ae/ar/information-and-services/education/school-education-k-12/stages-and-streams-of-school-education"]'::jsonb),
('AE','الإمارات العربية المتحدة','الثانوية','المسار المتقدم',NULL,'active','','generic','2026-2027','["https://www.moe.gov.ae/","https://u.ae/ar/information-and-services/education/school-education-k-12/stages-and-streams-of-school-education"]'::jsonb),
('AE','الإمارات العربية المتحدة','الثانوية','المسار المهني (التخصصي)',NULL,'transition-or-limited','','generic','2026-2027','["https://www.moe.gov.ae/","https://u.ae/ar/information-and-services/education/school-education-k-12/stages-and-streams-of-school-education"]'::jsonb),
('AE','الإمارات العربية المتحدة','الثانوية','مسار النخبة',NULL,'legacy-no-new-intake','','generic','2026-2027','["https://www.moe.gov.ae/","https://u.ae/ar/information-and-services/education/school-education-k-12/stages-and-streams-of-school-education"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','الآداب',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الإنسانية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الرياضية أ',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الرياضية ب',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','علوم الحياة والأرض',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الفيزيائية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الاقتصادية والتدبير',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','علوم التدبير المحاسباتي',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم والتكنولوجيات الميكانيكية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم والتكنولوجيات الكهربائية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','الفنون التطبيقية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','مسالك البكالوريا المهنية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الزراعية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('MA','المغرب','الثانوي التأهيلي','العلوم الشرعية',NULL,'active','','partial-digital-course','2026-2027','["https://www.men.gov.ma/","https://telmidtice.men.gov.ma/"]'::jsonb),
('SD','السودان','الثانوي','المساق العلمي',NULL,'active','','partial-detailed','2026-2027','["https://gmoe.gov.sd/?page_id=1343","https://mdl.edu.sd/"]'::jsonb),
('SD','السودان','الثانوي','المساق الأدبي',NULL,'active','','partial-detailed','2026-2027','["https://gmoe.gov.sd/?page_id=1343","https://mdl.edu.sd/"]'::jsonb),
('QA','قطر','الثانوي العام','المسار العلمي',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','الثانوي العام','مسار الآداب والإنسانيات',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','الثانوي العام','المسار التكنولوجي',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','الثانوي العام','المسار الموازي',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','مدرسة قطر للعلوم والتكنولوجيا — تكنولوجيا المعلومات',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','مدرسة قطر للعلوم والتكنولوجيا — الهندسة',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','مدرسة قطر للعلوم والتكنولوجيا — الطبي',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','المدارس التقنية',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','المدارس المصرفية وإدارة الأعمال',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','المعهد الديني — علمي',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('QA','قطر','المسارات والمدارس التخصصية','المعهد الديني — آداب وإنسانيات',NULL,'active','','generic','2026-2027','["https://www.edu.gov.qa/ar/Content/CurriculumSection"]'::jsonb),
('SY','سوريا','الثانوية العامة','الفرع العلمي',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('SY','سوريا','الثانوية العامة','الفرع الأدبي',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('SY','سوريا','الثانوية الشرعية','الشرعي',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('SY','سوريا','الثانوية المهنية','الصناعية',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('SY','سوريا','الثانوية المهنية','التجارية',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('SY','سوريا','الثانوية المهنية','النسوية',NULL,'active','','book-level','2026-2027','["https://moed.gov.sy/"]'::jsonb),
('IQ','العراق','المرحلة الإعدادية','العلمي',NULL,'active','shared-current-arabic-books','generic-book-bundle','2026-2027','["https://manahj.edu.iq/"]'::jsonb),
('IQ','العراق','المرحلة الإعدادية','الأدبي',NULL,'active','shared-current-arabic-books','generic-book-bundle','2026-2027','["https://manahj.edu.iq/"]'::jsonb),
('KW','الكويت','النظام الثانوي القائم','القسم العلمي',NULL,'active','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','النظام الثانوي القائم','القسم الأدبي',NULL,'active','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','مرحلة التأسيس والاستكشاف — الصف العاشر',NULL,'pilot-active','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','اللغات',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','القانون',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','العلوم الاجتماعية',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','التجاري',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','الرياضيات',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','العلوم',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','الصناعي',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('KW','الكويت','نظام مسارات — تطبيق محدود 2026-2027','التكنولوجيا والذكاء الاصطناعي',NULL,'future-after-foundation','','generic-book-bundle','2026-2027','["https://www.moe.edu.kw/news/1343","https://elibrary.moe.edu.kw/StudentsLibrary"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','جذع مشترك آداب',ARRAY[10]::integer[],'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','جذع مشترك علوم وتكنولوجيا',ARRAY[10]::integer[],'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','آداب وفلسفة',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','لغات أجنبية',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','علوم تجريبية',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','رياضيات',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','تقني رياضي',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','تسيير واقتصاد',NULL,'active','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('DZ','الجزائر','التعليم الثانوي','معلوماتية',NULL,'new-or-reorganized-2026-2027','','partial-detailed','2026-2027','["https://www.education.gov.dz/","https://www.onps.dz/"]'::jsonb),
('SA','السعودية','نظام المسارات','المسار العام',NULL,'active','','generic-or-track-extra-partial','2026-2027','["https://www.moe.gov.sa/ar/education/generaleducation/StudyPlans/Pages/Study-plans.aspx"]'::jsonb),
('SA','السعودية','نظام المسارات','مسار علوم الحاسب والهندسة',NULL,'active','','generic-or-track-extra-partial','2026-2027','["https://www.moe.gov.sa/ar/education/generaleducation/StudyPlans/Pages/Study-plans.aspx"]'::jsonb),
('SA','السعودية','نظام المسارات','مسار الصحة والحياة',NULL,'active','','generic-or-track-extra-partial','2026-2027','["https://www.moe.gov.sa/ar/education/generaleducation/StudyPlans/Pages/Study-plans.aspx"]'::jsonb),
('SA','السعودية','نظام المسارات','مسار إدارة الأعمال',NULL,'active','','generic-or-track-extra-partial','2026-2027','["https://www.moe.gov.sa/ar/education/generaleducation/StudyPlans/Pages/Study-plans.aspx"]'::jsonb),
('SA','السعودية','نظام المسارات','المسار الشرعي',NULL,'active','','generic-or-track-extra-partial','2026-2027','["https://www.moe.gov.sa/ar/education/generaleducation/StudyPlans/Pages/Study-plans.aspx"]'::jsonb),
('YE','اليمن','الثانوي','القسم العلمي',NULL,'active','shared-books-unless-verified-otherwise','book-level','2026-2027','["https://e-learning-moe.edu.ye/lcms/"]'::jsonb),
('YE','اليمن','الثانوي','القسم الأدبي',NULL,'active','shared-books-unless-verified-otherwise','book-level','2026-2027','["https://e-learning-moe.edu.ye/lcms/"]'::jsonb),
('DJ','جيبوتي','الثانوي العام','L',NULL,'active','','detailed-partial-to-strong','2026-2027','["https://cripen.dj/"]'::jsonb),
('DJ','جيبوتي','الثانوي العام','ES',NULL,'active','','detailed-partial-to-strong','2026-2027','["https://cripen.dj/"]'::jsonb),
('DJ','جيبوتي','الثانوي العام','S',NULL,'active','','detailed-partial-to-strong','2026-2027','["https://cripen.dj/"]'::jsonb),
('DJ','جيبوتي','الثانوي العام','SG',NULL,'active','','detailed-partial-to-strong','2026-2027','["https://cripen.dj/"]'::jsonb),
('SO','الصومال','الثانوي','الثانوي العام',NULL,'active','','generic','2026-2027','["https://moe.gov.so/"]'::jsonb),
('SO','الصومال','الثانوي','الثانوي التقني',NULL,'active','','generic','2026-2027','["https://moe.gov.so/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','A1',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','A2',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','A4',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','C',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','D',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','G',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','STI',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb),
('KM','جزر القمر','الثانوي الأعلى','STC',NULL,'current-national-exam-evidence','','structure-only','2026-2027','["https://mineducomores.gouv.km/"]'::jsonb)
on conflict (country_code, system_name_ar, track_name_ar, academic_year)
do update set
  country_name_ar = excluded.country_name_ar,
  grades = excluded.grades,
  status = excluded.status,
  arabic_policy = excluded.arabic_policy,
  lesson_coverage = excluded.lesson_coverage,
  source_urls = excluded.source_urls,
  is_active = true,
  updated_at = now();
